In [32]:
# importing numpy
import numpy as np


# Data and Attributes

In [ ]:
# Data Type in numPy - nd Array
a1 = np.array([1,2,3,4])
a1

In [3]:
a2 = np.array([[1,2,3],
             [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

### Attribute in numPy

In [9]:
# shape 
a1.shape

(4,)

In [12]:
#dimention - ndim
a1.ndim

1

In [13]:
#dtype - data type
a1.dtype

dtype('int32')

In [33]:
#size of array - size
a1.size


4

In [15]:
# type od data type 
type(a2)

numpy.ndarray

## Creating Array

In [20]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [36]:
#random array generate 
random1 = np.random.randint(0,10,size=(2,3))
random1

array([[4, 2, 3],
       [1, 5, 7]])

In [40]:
# random -2
random2 = np.random.random((2,3))
random2

array([[0.96269657, 0.85530787, 0.50426   ],
       [0.04802613, 0.82453968, 0.27904173]])

In [42]:
# random-3 
random3 = np.random.rand(2,3)
random3

array([[0.44926347, 0.15335956, 0.50026544],
       [0.53679812, 0.02915465, 0.7638666 ]])

In [44]:
#pheudom random number
np.random.seed()