In [1]:
# importing numpy
import numpy as np


# Data and Attributes

In [17]:
# Data Type in numPy - nd Array
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [8]:
a2 = np.array([[1,2,3],
        
               [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

### Attribute in numPy

In [9]:
# shape 
a1.shape

(4,)

In [12]:
#dimention - ndim
a1.ndim

1

In [13]:
#dtype - data type
a1.dtype

dtype('int32')

In [33]:
#size of array - size
a1.size


4

In [15]:
# type od data type 
type(a2)

numpy.ndarray

## Creating Array

In [20]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [6]:
#random array generate 
random1 = np.random.randint(0,10,size=(2,3))
random1

array([[9, 7, 4],
       [6, 7, 6]])

In [40]:
# random -2
random2 = np.random.random((2,3))
random2

array([[0.96269657, 0.85530787, 0.50426   ],
       [0.04802613, 0.82453968, 0.27904173]])

In [2]:
# random-3 
random3 = np.random.rand(2,3)
random3


array([[0.36898882, 0.07993531, 0.97480959],
       [0.89661986, 0.85148707, 0.16018241]])

In [3]:
#pheudom random number
np.random.seed()

# View array and Matrix

In [7]:
np.unique(random1)

array([4, 6, 7, 9])

In [9]:
a2


array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2[0]

array([1, 2, 3])

In [12]:
a2[1]

array([4, 5, 6])

In [13]:
#slicing also used 

# Manipulating and Comparing Arrays

## Arithmetic

In [14]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [15]:
#manipulating arrays
ones = np.ones(3)
ones

array([1., 1., 1.])

In [20]:
ones+a2



array([[2., 3., 4.],
       [5., 6., 7.]])

In [21]:
ones*a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
# a1/ones
# operands could not be broadcast together with shapes (4,) (3,) 

In [24]:
a2/ones

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
a2//ones


array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
a2**ones


array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [29]:
a2%ones

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
a2/2


array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [31]:
np.exp(a2)


array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [32]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])